### ISSUE TITLE
basic components & pages before dashboard

### ISSUE THREAD

**Issue by leicester70** [leicester70/first-mern-app#3]
refer to `journal\diagrams\flow.drawio` under [documentation branch](https://github.com/leicester70/first-mern-app/tree/documentation).

**Pages**, for this issue stops up till dashboard (from the `flow.drawio` file)
- [x] Landing Page
- [x] Sign Up
- [x] Login

**Components**
~~- [x] #39~~

Doesn't need to interact with backend yet. we can do that later.
edit: i made it work with the backend on the fly anyways

**Comment by alanantony24** [comment]
@leicester70 I have added files in my own branch, check out the commit here : [https://github.com/leicester70/first-mern-app/commit/00e948770e82edc6d9fba716dba8025775b81dad](url)
So I work on the contents of the page now ah?

**Comment by leicester70** [comment]
@alanantony24 

I havent start this issue still open, you can start on the components/pages mentioned [at the top](https://github.com/leicester70/first-mern-app/issues/3#issue-1552171775)

play around with [MUI library](https://mui.com/)

**Comment by leicester70** [comment]
Reopened because `NavBar.js` still needs work, this one comes later once sign up/in works fine and we get out landing page looking good
