### ISSUE TITLE
Component :  Landing Page

### ISSUE THREAD

**Issue by alanantony24** [leicester70/first-mern-app#31]
- [x] Create the Landing Page component
- [x] Come up with a decent UI
- [x] Link the Landing Page with the Sign-Up and Login Pages using Routes (I think ah I have no clue whether it's right lol?)

**Comment by alanantony24** [comment]
yo, @leicester70 I have done the routing for the signup page by pulling your code to my branch, since you're still working on the login page, I don't wanna f up by adding a placeholder component so I will route that page when you have pushed your changes 👍 holla me when you done💯

**Comment by leicester70** [comment]
> yo, @leicester70 I have done the routing for the signup page by pulling your code to my branch, since you're still working on the login page, I don't wanna f up by adding a placeholder component so I will route that page when you have pushed your changes 👍 holla me when you done💯

very cool, later i pull have a look

**Comment by leicester70** [comment]
- [ ] layout and grids
- [ ] design a little bit
- [ ] ui writing

**Comment by leicester70** [comment]
- [ ] layout and grids
- [ ] design a little bit
- [ ] ui writing

**Comment by leicester70** [comment]
- [ ] prepare color scheme
- [ ] prepare JSON data for <ThemeProvider/>
