### ISSUE TITLE
Implement Rate Limiter

### ISSUE THREAD

**Issue by leicester70** [leicester70/first-mern-app#35]
see security tab

this fix important so that I don't get spammed into oblivion by some stranger on the internet and make mongoDB bill me billions

**Comment by alanantony24** [comment]
@leicester70 eh can I try fix this?

**Comment by leicester70** [comment]
> @leicester70 eh can I try fix this?

Yeah sure, feel free too, u have a local one right? Can go research about rate limiters then try implement. My idea to test was to spam with postman lol

as long don't spam the cloud mongo 🥲

**Comment by alanantony24** [comment]
I tested with Postman, with and without the rate limiter. And the rate limiter works, now I have set it up in a way that it allows 5 HTTP requests in one minute 👍

**Comment by alanantony24** [comment]
hope I didn't spam the mongo too much HAHAHAHA

**Comment by leicester70** [comment]
> I tested with Postman, with and without the rate limiter. And the rate limiter works, now I have set it up in a way that it allows 5 HTTP requests in one minute 👍

ure so cool alan

**Comment by leicester70** [comment]
> hope I didn't spam the mongo too much HAHAHAHA

nah is okay, just drop the 'user' collection under the 'main' db if its too fucked

**Comment by leicester70** [comment]
oh ya i pulled lincoln in @alanantony24  lol we got new buddy

**Comment by alanantony24** [comment]
it's okay I think I was just spamming the get user API only so still okay 😸

**Comment by alanantony24** [comment]
I make a PR now
